### ISSUE TITLE
pip install qmix fails on Windows Anaconda

### ISSUE THREAD

**Issue by PaulKGrimes** [garrettj403/QMix#2]
When trying to install the qmix package using pip on Windows, the install fails with
```Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\pgrimes\AppData\Local\Temp\pip-install-c0f6g4ip\qmix\setup.py", line 24, in <module>
        long_description=read('README.md'),
      File "C:\Users\pgrimes\AppData\Local\Temp\pip-install-c0f6g4ip\qmix\setup.py", line 5, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "D:\Software\Anaconda2\envs\qmix-pip2\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3039: character maps to <undefined>
```

This appears to be due to non-standard characters in the README.md file, particularly in the Withington et al reference, where different quotation marks and hyphens are used.

**Comment by garrettj403** [comment]
Thank you for pointing this out. I was previously reading in `README.md` in order to generate the description, but I've now updated the description so that this doesn't happen anymore.
